"""API request/response schemas grouped by resource module."""

from .model_chat import (
    ModelGatewayMessage,
    ModelChatRequest,
    ModelGatewayUsage,
    ModelChatResponse,
)
from .langbot import (
    LangBotConversation,
    LangBotSender,
    LangBotMessage,
    LangBotWebhookRequest,
)
from .remote_control import (
    RemoteControlBridgeResponseTarget,
    RemoteControlBridgeSessionResponse,
    RemoteControlBridgeSessionListResponse,
    RemoteControlBridgeReplayResponse,
    remote_control_bridge_response,
)
from .tasks import (
    TaskCreateRequest,
    TaskResponse,
    TaskListResponse,
    TaskSubmissionResponse,
    ApprovalResponse,
    ApprovalListResponse,
    ApprovalDecisionRequest,
    ApprovalDecisionResponse,
    task_response,
    approval_response,
)
from .conversations import (
    ConversationCreateRequest,
    ConversationActorRequest,
    ConversationResponse,
    ConversationListResponse,
    ConversationMessageResponse,
    ConversationMessageListResponse,
    conversation_response,
    conversation_message_response,
)
from .capabilities import (
    CapabilityResponse,
    CapabilityCatalogResponse,
    capability_response,
)
from .skills import (
    SkillResponse,
    SkillListResponse,
    SkillCreateRequest,
    SkillActorRequest,
    skill_response,
)
from .accounts import (
    AccountConnectionCreateRequest,
    AccountConnectionActorRequest,
    AccountConnectionResponse,
    AccountConnectionListResponse,
    account_connection_response,
)
from .knowledge import (
    KnowledgeImportResponse,
    KnowledgeDocumentResponse,
    KnowledgeDocumentListResponse,
    KnowledgeDeleteResponse,
    KnowledgeSearchItem,
    KnowledgeSearchResponse,
)
from .notifications import (
    ReminderCreateRequest,
    ReminderActorRequest,
    ReminderResponse,
    ReminderListResponse,
    DesktopNotificationResponse,
    DesktopNotificationListResponse,
)

__all__ = [
    "ModelGatewayMessage",
    "ModelChatRequest",
    "ModelGatewayUsage",
    "ModelChatResponse",
    "LangBotConversation",
    "LangBotSender",
    "LangBotMessage",
    "LangBotWebhookRequest",
    "RemoteControlBridgeResponseTarget",
    "RemoteControlBridgeSessionResponse",
    "RemoteControlBridgeSessionListResponse",
    "RemoteControlBridgeReplayResponse",
    "remote_control_bridge_response",
    "TaskCreateRequest",
    "TaskResponse",
    "TaskListResponse",
    "TaskSubmissionResponse",
    "ApprovalResponse",
    "ApprovalListResponse",
    "ApprovalDecisionRequest",
    "ApprovalDecisionResponse",
    "task_response",
    "approval_response",
    "ConversationCreateRequest",
    "ConversationActorRequest",
    "ConversationResponse",
    "ConversationListResponse",
    "ConversationMessageResponse",
    "ConversationMessageListResponse",
    "conversation_response",
    "conversation_message_response",
    "CapabilityResponse",
    "CapabilityCatalogResponse",
    "capability_response",
    "SkillResponse",
    "SkillListResponse",
    "SkillCreateRequest",
    "SkillActorRequest",
    "skill_response",
    "AccountConnectionCreateRequest",
    "AccountConnectionActorRequest",
    "AccountConnectionResponse",
    "AccountConnectionListResponse",
    "account_connection_response",
    "KnowledgeImportResponse",
    "KnowledgeDocumentResponse",
    "KnowledgeDocumentListResponse",
    "KnowledgeDeleteResponse",
    "KnowledgeSearchItem",
    "KnowledgeSearchResponse",
    "ReminderCreateRequest",
    "ReminderActorRequest",
    "ReminderResponse",
    "ReminderListResponse",
    "DesktopNotificationResponse",
    "DesktopNotificationListResponse",
]
