SEARCH_WEB_TOOL_NAME = "search.web"
TOOL_STATUS_SUCCEEDED = "succeeded"
TOOL_STATUS_FAILED = "failed"
PROVIDER_TAVILY = "tavily"
PROVIDER_BRAVE = "brave"
PROVIDER_DUCKDUCKGO = "duckduckgo"
DEFAULT_SEARCH_PROVIDER_ORDER = (
    PROVIDER_TAVILY,
    PROVIDER_BRAVE,
    PROVIDER_DUCKDUCKGO,
)
