from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
import hashlib
import json
from pathlib import Path
from typing import Mapping

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from application.enterprise_runtime import GovernanceAuditInput, GovernanceAuditService
from application.lifecycle_hooks import LifecycleHookRegistry, build_lifecycle_event
from application.session_context.context_snapshots import TaskContextSnapshotService
from domain.models import (
    AgentRun,
    ArtifactRecord,
    Conversation,
    Task,
    TaskContextSnapshot,
    new_id,
    utc_now,
)
from tools.builtin.artifacts import ArtifactPathError, ArtifactStore

_MAX_ARTIFACT_BYTES = 25 * 1024 * 1024
_SUPPORTED_VISIBILITY = {"private", "conversation"}
_SUPPORTED_SENSITIVITY = {"normal", "sensitive", "restricted"}
_DOWNLOADABLE_STATES = {"registered", "archived"}


class ArtifactLifecycleError(RuntimeError):
    """定义当前组件可安全处理的错误类型。"""

    code = "artifact_operation_failed"
    status_code = 400


class ArtifactUnavailableError(ArtifactLifecycleError):
    """定义当前组件可安全处理的错误类型。"""

    code = "artifact_unavailable"
    status_code = 404


class ArtifactValidationError(ArtifactLifecycleError):
    """定义当前组件可安全处理的错误类型。"""

    code = "artifact_invalid"
    status_code = 422


@dataclass(frozen=True)
class ArtifactView:
    """定义当前组件的职责和边界。"""

    id: str  # id 对应的数据字段。
    tenant_id: str  # tenant_id 对应的数据字段。
    organization_id: str | None  # organization_id 对应的数据字段。
    owner_type: str  # owner_type 对应的数据字段。
    owner_id: str  # owner_id 对应的数据字段。
    conversation_id: str | None  # conversation_id 对应的数据字段。
    task_id: str  # task_id 对应的数据字段。
    run_id: str | None  # run_id 对应的数据字段。
    filename: str  # filename 对应的数据字段。
    media_type: str  # media_type 对应的数据字段。
    size_bytes: int  # size_bytes 对应的数据字段。
    content_hash: str  # content_hash 对应的数据字段。
    version: str  # version 对应的数据字段。
    generation_method: str  # generation_method 对应的数据字段。
    source_reference_versions: dict[str, str]  # source_reference_versions 对应的数据字段。
    visibility: str  # visibility 对应的数据字段。
    sensitivity: str  # sensitivity 对应的数据字段。
    lifecycle_state: str  # lifecycle_state 对应的数据字段。
    publication_state: str  # publication_state 对应的数据字段。
    retention_state: str  # retention_state 对应的数据字段。
    created_at: datetime  # created_at 对应的数据字段。
    updated_at: datetime  # updated_at 对应的数据字段。
    archived_at: datetime | None  # archived_at 对应的数据字段。
    revoked_at: datetime | None  # revoked_at 对应的数据字段。


@dataclass(frozen=True)
class ArtifactDownload:
    """定义当前组件的职责和边界。"""

    artifact_id: str  # artifact_id 对应的数据字段。
    path: Path  # path 对应的数据字段。
    filename: str  # filename 对应的数据字段。
    media_type: str  # media_type 对应的数据字段。
    size_bytes: int  # size_bytes 对应的数据字段。


@dataclass(frozen=True)
class ArtifactContextInput:
    """定义当前组件的职责和边界。"""

    id: str  # id 对应的数据字段。
    path: Path  # path 对应的数据字段。
    filename: str  # filename 对应的数据字段。
    content_hash: str  # content_hash 对应的数据字段。
    version: str  # version 对应的数据字段。
    size_bytes: int  # size_bytes 对应的数据字段。


class ArtifactLifecycleService:
    """定义当前组件的职责和边界。"""

    def __init__(
        self,
        session: AsyncSession,
        *,
        store: ArtifactStore,
        auto_commit: bool = True,
        lifecycle_registry: LifecycleHookRegistry | None = None,
    ) -> None:
        """Bind one database transaction and one backend-owned Artifact store.

        Args:
            session: 当前数据库异步会话。
            store: 用于执行当前操作的 store 参数。
            auto_commit: 用于执行当前操作的 auto commit 参数。
            lifecycle_registry: 用于执行当前操作的 lifecycle registry 参数。
        """
        self.session = session
        self.store = store
        self.auto_commit = auto_commit
        self.lifecycle_registry = lifecycle_registry

    async def register_bytes(
        self,
        *,
        task_id: str,
        actor_user_id: str,
        filename: str,
        media_type: str,
        data: bytes,
        generation_method: str,
        idempotency_key: str,
        visibility: str = "private",
        sensitivity: str = "normal",
    ) -> ArtifactView:
        """Persist immutable generated bytes and trusted Task snapshot provenance.

        Args:
            task_id: 目标任务 ID。
            actor_user_id: 发起当前操作的用户 ID。
            filename: 用于执行当前操作的 filename 参数。
            media_type: 用于执行当前操作的 media type 参数。
            data: 需要处理或持久化的数据。
            generation_method: 用于执行当前操作的 generation method 参数。
            idempotency_key: 用于识别重复请求的幂等键。
            visibility: 用于执行当前操作的 visibility 参数。
            sensitivity: 用于执行当前操作的 sensitivity 参数。
        """
        normalized = _validate_registration(
            filename=filename,
            media_type=media_type,
            data=data,
            generation_method=generation_method,
            idempotency_key=idempotency_key,
            visibility=visibility,
            sensitivity=sensitivity,
        )
        task = await self._owned_task(task_id=task_id, actor_user_id=actor_user_id)
        if normalized.visibility == "conversation" and task.conversation_id is None:
            raise ArtifactValidationError(
                "Conversation visibility requires a Conversation"
            )
        content_hash = hashlib.sha256(data).hexdigest()
        existing = await self.session.scalar(
            select(ArtifactRecord).where(
                ArtifactRecord.task_id == task.id,
                ArtifactRecord.idempotency_key == normalized.idempotency_key,
            )
        )
        if existing is not None:
            self._assert_idempotent_match(
                existing,
                filename=normalized.filename,
                media_type=normalized.media_type,
                generation_method=normalized.generation_method,
                visibility=normalized.visibility,
                sensitivity=normalized.sensitivity,
                content_hash=content_hash,
                size_bytes=len(data),
            )
            return _view(existing)

        snapshot = await self.session.scalar(
            select(TaskContextSnapshot).where(TaskContextSnapshot.task_id == task.id)
        )
        if snapshot is None:
            snapshot = await TaskContextSnapshotService(self.session).create_initial(
                task
            )
        run_id = await self.session.scalar(
            select(AgentRun.id)
            .where(AgentRun.task_id == task.id)
            .order_by(AgentRun.attempt_no.desc())
            .limit(1)
        )
        artifact_id = new_id()
        suffix = Path(normalized.filename).suffix.lower()
        try:
            target = self.store.reserve_immutable(
                task_id=task.id,
                artifact_id=artifact_id,
                suffix=suffix,
            )
            self.store.atomic_write_immutable(target, data)
            inspection = self.store.inspect(
                task_id=task.id,
                reference=target.relative_to(self.store.root).as_posix(),
            )
        except (ArtifactPathError, OSError) as exc:
            raise ArtifactValidationError("Artifact storage is unavailable") from exc
        if inspection.content_hash != content_hash or inspection.size_bytes != len(
            data
        ):
            inspection.path.unlink(missing_ok=True)
            raise ArtifactValidationError("Artifact content verification failed")

        record = ArtifactRecord(
            id=artifact_id,
            tenant_id=snapshot.tenant_id,
            organization_id=snapshot.organization_id,
            owner_type=snapshot.owner_type,
            owner_id=snapshot.owner_id,
            conversation_id=snapshot.conversation_id,
            task_id=task.id,
            run_id=run_id,
            created_by=actor_user_id,
            display_filename=normalized.filename,
            storage_reference=inspection.path.relative_to(self.store.root).as_posix(),
            media_type=normalized.media_type,
            size_bytes=inspection.size_bytes,
            content_hash=inspection.content_hash,
            version="1",
            generation_method=normalized.generation_method,
            idempotency_key=normalized.idempotency_key,
            source_reference_versions_json=_encode_source_versions(
                snapshot.resolved_resource_versions_json
            ),
            visibility=normalized.visibility,
            sensitivity=normalized.sensitivity,
            lifecycle_state="registered",
            publication_state="unpublished",
            retention_state="retained",
        )
        self.session.add(record)
        try:
            await self.session.flush()
            if self.auto_commit:
                await self.session.commit()
        except Exception:
            await self.session.rollback()
            inspection.path.unlink(missing_ok=True)
            raise
        if self.auto_commit:
            await self._dispatch_lifecycle_observer(
                record, event_type="artifact.registered"
            )
        return _view(record)

    async def list_conversation(
        self,
        *,
        conversation_id: str,
        actor_user_id: str,
    ) -> tuple[ArtifactView, ...]:
        """List non-revoked Artifact metadata for one exactly owned Conversation.

        Args:
            conversation_id: 目标会话 ID。
            actor_user_id: 发起当前操作的用户 ID。
        """
        conversation = await self.session.scalar(
            select(Conversation).where(
                Conversation.id == conversation_id,
                Conversation.user_id == actor_user_id,
            )
        )
        if conversation is None:
            raise ArtifactUnavailableError("Conversation Artifacts are unavailable")
        rows = tuple(
            await self.session.scalars(
                select(ArtifactRecord)
                .where(
                    ArtifactRecord.conversation_id == conversation.id,
                    ArtifactRecord.owner_type == "user",
                    ArtifactRecord.owner_id == actor_user_id,
                    ArtifactRecord.created_by == actor_user_id,
                    ArtifactRecord.visibility.in_(_SUPPORTED_VISIBILITY),
                    ArtifactRecord.lifecycle_state.in_(_DOWNLOADABLE_STATES),
                )
                .order_by(ArtifactRecord.created_at.desc(), ArtifactRecord.id.desc())
            )
        )
        return tuple(_view(row) for row in rows)

    async def resolve_download(
        self,
        *,
        artifact_id: str,
        actor_user_id: str,
    ) -> ArtifactDownload:
        """Re-authorize and integrity-check one download while auditing the decision.

        Args:
            artifact_id: 目标产物 ID。
            actor_user_id: 发起当前操作的用户 ID。
        """
        record = await self.session.get(ArtifactRecord, artifact_id)
        if record is None:
            raise ArtifactUnavailableError("Artifact is unavailable")
        if not self._is_owned_and_visible(record, actor_user_id):
            await self._audit(
                record,
                actor_user_id=actor_user_id,
                decision="DENY",
                result_status="owner_scope_denied",
                summary="Artifact download denied by owner scope",
            )
            raise ArtifactUnavailableError("Artifact is unavailable")
        if record.lifecycle_state not in _DOWNLOADABLE_STATES:
            await self._audit(
                record,
                actor_user_id=actor_user_id,
                decision="DENY",
                result_status="lifecycle_denied",
                summary="Artifact download denied by lifecycle state",
            )
            raise ArtifactUnavailableError("Artifact is unavailable")
        try:
            inspection = self.store.inspect(
                task_id=record.task_id,
                reference=record.storage_reference,
            )
        except (ArtifactPathError, OSError):
            await self._audit(
                record,
                actor_user_id=actor_user_id,
                decision="DENY",
                result_status="integrity_failed",
                summary="Artifact download failed integrity verification",
            )
            raise ArtifactUnavailableError("Artifact is unavailable") from None
        if (
            inspection.content_hash != record.content_hash
            or inspection.size_bytes != record.size_bytes
        ):
            await self._audit(
                record,
                actor_user_id=actor_user_id,
                decision="DENY",
                result_status="integrity_failed",
                summary="Artifact download failed integrity verification",
            )
            raise ArtifactUnavailableError("Artifact is unavailable")
        await self._audit(
            record,
            actor_user_id=actor_user_id,
            decision="ALLOW",
            result_status="download_resolved",
            summary="Artifact download authorized and resolved",
        )
        return ArtifactDownload(
            artifact_id=record.id,
            path=inspection.path,
            filename=record.display_filename,
            media_type=record.media_type,
            size_bytes=record.size_bytes,
        )

    async def resolve_context_input(
        self,
        *,
        artifact_id: str,
        actor_user_id: str,
        conversation_id: str,
    ) -> ArtifactContextInput:
        """Resolve one context Artifact without creating a download audit event.

        Args:
            artifact_id: 目标产物 ID。
            actor_user_id: 发起当前操作的用户 ID。
            conversation_id: 目标会话 ID。
        """
        record = await self._owned_record(artifact_id, actor_user_id)
        if (
            record.conversation_id != conversation_id
            or record.lifecycle_state not in _DOWNLOADABLE_STATES
        ):
            raise ArtifactUnavailableError("Artifact is unavailable")
        try:
            inspection = self.store.inspect(
                task_id=record.task_id,
                reference=record.storage_reference,
            )
        except (ArtifactPathError, OSError) as exc:
            raise ArtifactUnavailableError("Artifact is unavailable") from exc
        if (
            inspection.content_hash != record.content_hash
            or inspection.size_bytes != record.size_bytes
        ):
            raise ArtifactUnavailableError("Artifact is unavailable")
        return ArtifactContextInput(
            id=record.id,
            path=inspection.path,
            filename=record.display_filename,
            content_hash=record.content_hash,
            version=record.version,
            size_bytes=record.size_bytes,
        )

    async def archive(
        self,
        *,
        artifact_id: str,
        actor_user_id: str,
    ) -> ArtifactView:
        """Archive an owned Artifact idempotently without deleting managed bytes.

        Args:
            artifact_id: 目标产物 ID。
            actor_user_id: 发起当前操作的用户 ID。
        """
        record = await self._owned_record(artifact_id, actor_user_id)
        if record.lifecycle_state == "revoked":
            raise ArtifactUnavailableError("Artifact is unavailable")
        if record.lifecycle_state != "archived":
            record.lifecycle_state = "archived"
            record.archived_at = utc_now()
            await self._audit(
                record,
                actor_user_id=actor_user_id,
                decision="ALLOW",
                result_status="archived",
                summary="Artifact archived without deleting retained bytes",
            )
            await self._dispatch_lifecycle_observer(
                record, event_type="artifact.archived"
            )
        return _view(record)

    async def revoke(
        self,
        *,
        artifact_id: str,
        actor_user_id: str,
    ) -> ArtifactView:
        """Revoke an owned Artifact idempotently while retaining governance facts.

        Args:
            artifact_id: 目标产物 ID。
            actor_user_id: 发起当前操作的用户 ID。
        """
        record = await self._owned_record(artifact_id, actor_user_id)
        if record.lifecycle_state != "revoked":
            record.lifecycle_state = "revoked"
            record.revoked_at = utc_now()
            await self._audit(
                record,
                actor_user_id=actor_user_id,
                decision="ALLOW",
                result_status="revoked",
                summary="Artifact access revoked while audit facts remain retained",
            )
            await self._dispatch_lifecycle_observer(
                record, event_type="artifact.revoked"
            )
        return _view(record)

    async def managed_reference(
        self,
        *,
        artifact_id: str,
        task_id: str,
        actor_user_id: str,
    ) -> str:
        """Return a managed reference only to the internal owning producer boundary.

        Args:
            artifact_id: 目标产物 ID。
            task_id: 目标任务 ID。
            actor_user_id: 发起当前操作的用户 ID。
        """
        record = await self._owned_record(artifact_id, actor_user_id)
        if record.task_id != task_id:
            raise ArtifactUnavailableError("Artifact is unavailable")
        return record.storage_reference

    async def _owned_task(self, *, task_id: str, actor_user_id: str) -> Task:
        """Resolve one Task without revealing cross-owner identities.

        Args:
            task_id: 目标任务 ID。
            actor_user_id: 发起当前操作的用户 ID。
        """
        task = await self.session.scalar(
            select(Task).where(Task.id == task_id, Task.user_id == actor_user_id)
        )
        if task is None or (task.owner_id not in {None, actor_user_id}):
            raise ArtifactUnavailableError("Task is unavailable")
        return task

    async def _owned_record(
        self, artifact_id: str, actor_user_id: str
    ) -> ArtifactRecord:
        """Resolve an Artifact only when exact user ownership remains valid.

        Args:
            artifact_id: 目标产物 ID。
            actor_user_id: 发起当前操作的用户 ID。
        """
        record = await self.session.get(ArtifactRecord, artifact_id)
        if record is None or not self._is_owned_and_visible(record, actor_user_id):
            raise ArtifactUnavailableError("Artifact is unavailable")
        return record

    @staticmethod
    def _is_owned_and_visible(record: ArtifactRecord, actor_user_id: str) -> bool:
        """Apply the currently supported fail-closed Artifact visibility policy.

        Args:
            record: 用于执行当前操作的 record 参数。
            actor_user_id: 发起当前操作的用户 ID。
        """
        return (
            record.owner_type == "user"
            and record.owner_id == actor_user_id
            and record.created_by == actor_user_id
            and record.visibility in _SUPPORTED_VISIBILITY
        )

    @staticmethod
    def _assert_idempotent_match(
        record: ArtifactRecord,
        *,
        filename: str,
        media_type: str,
        generation_method: str,
        visibility: str,
        sensitivity: str,
        content_hash: str,
        size_bytes: int,
    ) -> None:
        """Reject reuse of an idempotency key for different immutable content.

        Args:
            record: 用于执行当前操作的 record 参数。
            filename: 用于执行当前操作的 filename 参数。
            media_type: 用于执行当前操作的 media type 参数。
            generation_method: 用于执行当前操作的 generation method 参数。
            visibility: 用于执行当前操作的 visibility 参数。
            sensitivity: 用于执行当前操作的 sensitivity 参数。
            content_hash: 用于执行当前操作的 content hash 参数。
            size_bytes: 用于执行当前操作的 size bytes 参数。
        """
        if (
            record.display_filename != filename
            or record.media_type != media_type
            or record.generation_method != generation_method
            or record.visibility != visibility
            or record.sensitivity != sensitivity
            or record.content_hash != content_hash
            or record.size_bytes != size_bytes
        ):
            raise ArtifactValidationError("Artifact idempotency key conflicts")

    async def _dispatch_lifecycle_observer(
        self,
        record: ArtifactRecord,
        *,
        event_type: str,
    ) -> None:
        """Emit a path-free Artifact event after its core lifecycle fact commits.

        Args:
            record: 用于执行当前操作的 record 参数。
            event_type: 用于执行当前操作的 event type 参数。
        """
        if self.lifecycle_registry is None:
            return
        try:
            event = build_lifecycle_event(
                event_type=event_type,
                actor_user_id=record.created_by,
                tenant_id=record.tenant_id,
                organization_id=record.organization_id,
                conversation_id=record.conversation_id,
                task_id=record.task_id,
                run_id=record.run_id,
                payload={
                    "artifact_id": record.id,
                    "lifecycle_state": record.lifecycle_state,
                    "publication_state": record.publication_state,
                    "retention_state": record.retention_state,
                    "media_type": record.media_type,
                    "size_bytes": record.size_bytes,
                },
            )
            await self.lifecycle_registry.dispatch_observers(event)
        except Exception:
            return

    async def _audit(
        self,
        record: ArtifactRecord,
        *,
        actor_user_id: str,
        decision: str,
        result_status: str,
        summary: str,
    ) -> None:
        """Persist one bounded Artifact governance fact before returning a decision.

        Args:
            record: 用于执行当前操作的 record 参数。
            actor_user_id: 发起当前操作的用户 ID。
            decision: 当前操作的治理决策。
            result_status: 用于执行当前操作的 result status 参数。
            summary: 用于执行当前操作的 summary 参数。
        """
        await GovernanceAuditService(self.session).record(
            GovernanceAuditInput(
                tenant_id=record.tenant_id,
                subject_id=actor_user_id,
                organization_id=record.organization_id,
                conversation_id=record.conversation_id,
                task_id=record.task_id,
                run_id=record.run_id,
                resource_type="artifact",
                resource_id=record.id,
                policy_decision=decision,
                result_status=result_status,
                summary=summary,
            )
        )
        await self.session.commit()


@dataclass(frozen=True)
class _RegistrationInput:
    """定义当前组件的职责和边界。"""

    filename: str  # filename 对应的数据字段。
    media_type: str  # media_type 对应的数据字段。
    generation_method: str  # generation_method 对应的数据字段。
    idempotency_key: str  # idempotency_key 对应的数据字段。
    visibility: str  # visibility 对应的数据字段。
    sensitivity: str  # sensitivity 对应的数据字段。


def _validate_registration(
    *,
    filename: str,
    media_type: str,
    data: bytes,
    generation_method: str,
    idempotency_key: str,
    visibility: str,
    sensitivity: str,
) -> _RegistrationInput:
    """Normalize registration metadata and enforce fixed safe size and scope bounds.

    Args:
        filename: 用于执行当前操作的 filename 参数。
        media_type: 用于执行当前操作的 media type 参数。
        data: 需要处理或持久化的数据。
        generation_method: 用于执行当前操作的 generation method 参数。
        idempotency_key: 用于识别重复请求的幂等键。
        visibility: 用于执行当前操作的 visibility 参数。
        sensitivity: 用于执行当前操作的 sensitivity 参数。
    """
    safe_filename = filename.strip()
    safe_media_type = media_type.strip().lower()
    safe_method = generation_method.strip()
    safe_key = idempotency_key.strip()
    safe_visibility = visibility.strip().lower()
    safe_sensitivity = sensitivity.strip().lower()
    if (
        not safe_filename
        or len(safe_filename) > 255
        or Path(safe_filename).name != safe_filename
        or "/" in safe_filename
        or "\\" in safe_filename
        or "\x00" in safe_filename
        or not Path(safe_filename).suffix
    ):
        raise ArtifactValidationError("Artifact filename is invalid")
    if (
        not safe_media_type
        or len(safe_media_type) > 255
        or "/" not in safe_media_type
        or any(character.isspace() for character in safe_media_type)
    ):
        raise ArtifactValidationError("Artifact media type is invalid")
    if not isinstance(data, bytes) or not data or len(data) > _MAX_ARTIFACT_BYTES:
        raise ArtifactValidationError("Artifact content size is invalid")
    if (
        not safe_method
        or len(safe_method) > 128
        or any(ord(char) < 32 for char in safe_method)
    ):
        raise ArtifactValidationError("Artifact generation method is invalid")
    if not safe_key or len(safe_key) > 128 or any(ord(char) < 32 for char in safe_key):
        raise ArtifactValidationError("Artifact idempotency key is invalid")
    if safe_visibility not in _SUPPORTED_VISIBILITY:
        raise ArtifactValidationError("Artifact visibility is unsupported")
    if safe_sensitivity not in _SUPPORTED_SENSITIVITY:
        raise ArtifactValidationError("Artifact sensitivity is invalid")
    return _RegistrationInput(
        filename=safe_filename,
        media_type=safe_media_type,
        generation_method=safe_method,
        idempotency_key=safe_key,
        visibility=safe_visibility,
        sensitivity=safe_sensitivity,
    )


def _encode_source_versions(raw: str) -> str:
    """Normalize bounded source Reference versions from the trusted snapshot.

    Args:
        raw: 用于执行当前操作的 raw 参数。
    """
    try:
        payload = json.loads(raw)
    except (TypeError, json.JSONDecodeError):
        payload = {}
    if not isinstance(payload, Mapping):
        payload = {}
    safe = {
        str(key)[:512]: str(value)[:512]
        for key, value in list(payload.items())[:256]
        if isinstance(key, str)
        and isinstance(value, str)
        and key.strip()
        and value.strip()
    }
    return json.dumps(safe, ensure_ascii=False, separators=(",", ":"), sort_keys=True)


def _decode_source_versions(raw: str) -> dict[str, str]:
    """Decode only bounded string provenance values for the public view.

    Args:
        raw: 用于执行当前操作的 raw 参数。
    """
    try:
        payload = json.loads(raw)
    except (TypeError, json.JSONDecodeError):
        return {}
    if not isinstance(payload, Mapping):
        return {}
    return {
        key[:512]: value[:512]
        for key, value in list(payload.items())[:256]
        if isinstance(key, str) and isinstance(value, str) and key and value
    }


def _view(record: ArtifactRecord) -> ArtifactView:
    """Build a path-free immutable Artifact response from one persisted record.

    Args:
        record: 用于执行当前操作的 record 参数。
    """
    return ArtifactView(
        id=record.id,
        tenant_id=record.tenant_id,
        organization_id=record.organization_id,
        owner_type=record.owner_type,
        owner_id=record.owner_id,
        conversation_id=record.conversation_id,
        task_id=record.task_id,
        run_id=record.run_id,
        filename=record.display_filename,
        media_type=record.media_type,
        size_bytes=record.size_bytes,
        content_hash=record.content_hash,
        version=record.version,
        generation_method=record.generation_method,
        source_reference_versions=_decode_source_versions(
            record.source_reference_versions_json
        ),
        visibility=record.visibility,
        sensitivity=record.sensitivity,
        lifecycle_state=record.lifecycle_state,
        publication_state=record.publication_state,
        retention_state=record.retention_state,
        created_at=record.created_at,
        updated_at=record.updated_at,
        archived_at=record.archived_at,
        revoked_at=record.revoked_at,
    )
