from importlib import import_module


EXPECTED_EXPORTS = {
    "AccountConnection",
    "AgentRun",
    "AgentSchedule",
    "AgentScheduleRun",
    "Approval",
    "ApprovalStatus",
    "ApprovalType",
    "ArtifactRecord",
    "Base",
    "CapabilityDefinition",
    "CapabilityGrant",
    "CapabilityVersion",
    "Connector",
    "ConnectorInstance",
    "ConnectorTool",
    "ConnectionAuditLog",
    "Conversation",
    "ConversationMessage",
    "ConversationResourceReference",
    "ConversationSummary",
    "Credential",
    "DeliveryAttempt",
    "EvolutionChange",
    "EvolutionVersion",
    "GovernanceAudit",
    "ImportAudit",
    "KnowledgeChunk",
    "KnowledgeDocument",
    "LifecycleHookExecution",
    "LocalCredential",
    "LocalSession",
    "Memory",
    "MemoryBlock",
    "MemoryConsolidationDecision",
    "MemoryConsolidationDigest",
    "MemoryConsolidationRun",
    "MemoryEffectiveness",
    "MemoryEffectivenessEvent",
    "MemoryFeedback",
    "MemoryIndexOutbox",
    "MemoryLink",
    "MemoryPolicy",
    "MemoryReleaseReport",
    "MemoryRetrievalPolicyVersion",
    "MemoryRetrievalTrace",
    "MemoryRetrievalTraceItem",
    "ModelLog",
    "NotificationOutbox",
    "Organization",
    "OrganizationMembership",
    "PlatformAccount",
    "PolicyRule",
    "ProcessedMessage",
    "Reminder",
    "SkillAuditLog",
    "SkillDefinition",
    "SkillDraft",
    "SkillVersion",
    "Space",
    "SpaceMembership",
    "Task",
    "TaskContextSnapshot",
    "TaskEvent",
    "TaskStatus",
    "Tenant",
    "TimestampMixin",
    "ToolLog",
    "User",
    "new_id",
    "utc_now",
}

EXPECTED_TABLES = {
    "account_connections",
    "agent_runs",
    "agent_schedule_runs",
    "agent_schedules",
    "approvals",
    "artifacts",
    "capability_definitions",
    "capability_grants",
    "capability_versions",
    "connector_instances",
    "connector_tools",
    "connectors",
    "connection_audit_logs",
    "conversation_messages",
    "conversation_resource_references",
    "conversation_summaries",
    "conversations",
    "credentials",
    "delivery_attempts",
    "evolution_changes",
    "evolution_versions",
    "governance_audits",
    "import_audits",
    "knowledge_chunks",
    "knowledge_documents",
    "lifecycle_hook_executions",
    "local_credentials",
    "local_sessions",
    "memories",
    "memory_blocks",
    "memory_consolidation_decisions",
    "memory_consolidation_digests",
    "memory_consolidation_runs",
    "memory_effectiveness",
    "memory_effectiveness_events",
    "memory_feedback",
    "memory_index_outbox",
    "memory_links",
    "memory_policies",
    "memory_release_reports",
    "memory_retrieval_policy_versions",
    "memory_retrieval_trace_items",
    "memory_retrieval_traces",
    "model_logs",
    "notification_outbox",
    "organization_memberships",
    "organizations",
    "platform_accounts",
    "policy_rules",
    "processed_messages",
    "reminders",
    "skill_audit_logs",
    "skill_definitions",
    "skill_drafts",
    "skill_versions",
    "space_memberships",
    "spaces",
    "task_events",
    "task_context_snapshots",
    "tasks",
    "tenants",
    "tool_logs",
    "users",
}


def test_domain_models_public_exports_remain_available() -> None:
    """All existing public symbols stay available from domain.models."""
    models = import_module("domain.models")

    assert set(models.__all__) == EXPECTED_EXPORTS
    for name in EXPECTED_EXPORTS:
        assert getattr(models, name) is not None


def test_domain_models_metadata_registers_existing_tables() -> None:
    """Importing domain.models registers every ORM table on Base.metadata."""
    from domain.models import Base

    assert set(Base.metadata.tables) == EXPECTED_TABLES
